SMACB/CalendarioACB.py, SMACB/MercadoPage.py
=> Empty strings

GetSuperManagerMerged.py, SMACB/MercadoPage.py
SMACB/MercadoPage.py Mejora el control de tipos de la entrada
GetSuperManagerMerged.py Tiene en cuenta el mercado de entrada y de sa
lida y lo muestra si ha habido cambios.
=> 05_comparaMercados Corresponde a #15

InformeSuperManager3.py, SMACB/SuperManager.py
=> 04 columna diff precios

SMACB/MercadoPage.py, SMACB/SMconstants.py
Resuelve #55  (ignorada la parte de agrupar el listado)
=> Mejorada la info en el listado de jugadores

SMACB/SuperManager.py
=> Cambiada la gestión de excepciones en getIntoPrivateLeague

SMACB/CalendarioACB.py, SMACB/PartidoACB.py, SMACB/TemporadaACB.py, Utils/Misc.py
Arregla la captura de calendarios por motivos diversos. Todo correcto hasta la Ed 46 (que hay un partido impugnado con 2-0), en la 38 hay una inconsistencia de resultado. A partir de la 37 fallan partidos en proporción creciente. La ACB empieza en la temp 28
=> 27 arregla temp 55

DescargaTemporada.py, SMACB/CalendarioACB.py, SMACB/PartidoACB.py, SMACB/PlantillaACB.py, SMACB/SMconstants.py, SMACB/TemporadaACB.py, Utils/Web.py
Adapta el código de descarga de temporada a los cambios en la página de la ACB
=> 31 cambios pagina acb

DescargaTemporada.py, SMACB/CalendarioACB.py, SMACB/PartidoACB.py, SMACB/PlantillaACB.py, SMACB/SMconstants.py, SMACB/TemporadaACB.py, Utils/Web.py
* Utils/Web.py: añadida función para sacar ID de enlace WWW
* Adds a default result to getObjID
* Codigo para descargar plantilla y buscar códigos perdidos
* Añadida búsqueda de código de persona a partir de nombre
* Actualizada descarga de temporada con partidos y plantillas
=> 31 cambios pagina acb (#70)

SMACB/CalendarioACB.py
Para partidos aplazados que aún no tienen fecha. La fija a NEVER
=> 37 problema en partidos equipos

DescargaTemporada.py, SMACB/MercadoPage.py, SMACB/PlantillaACB.py, SMACB/SuperManager.py, SMACB/TemporadaACB.py, Utils/BoWtraductor.py, Utils/LoggedDict.py, Utils/LoggedValue.py, bin/generaPrograma.py, requirements-dev.txt, tests/utils/test_loggedDict.py, tests/utils/test_loggedValue.py
Compara la situación de las plantillas y almacena los cambios
Introduce Las estructuras Logged* para almacenar cosas susceptibles de cambiar durante la temporada.
=> 45 activos y bajas

SMACB/TemporadaACB.py, bin/generaPrograma.py, requirements.txt
* Arregla la ejecución por cambios en Pandas, Numpy...
* Arregla la presentación cuando los datos son Null en la info de los jugadores
* Muestra los equipos con balance negativo en la tabla de la liga
* Mejora (algo) la forma de mostrar cuando los equipos tienen diferente número de partidos
=> 47 programa de mano

Utils/BoWtraductor.py, Utils/Web.py, requirements-dev.txt, requirements.txt
Usa python 3.12
Actualización de paquetes
=> 54 Cambios requeridos para silenciar warnings con Fedora39

Utils/BoWtraductor.py, Utils/Web.py, requirements-dev.txt, requirements.txt
* requirements.txt: updated packages
* Updated packages
* Adaptados patrones a nueva syntax de Python 3.12
=> Sync 20231125 

SMACB/Programa.py, SMACB/TemporadaACB.py, bin/generaPrograma.py
La genera correctamente. Queda pendiente
=> 52 Tabla de clasificación en el programa

SMACB/Programa.py, SMACB/TemporadaACB.py, bin/generaPrograma.py
Resuelve la primera parte de #144  (sigPartido). Elimina referencias a Izda-Dcha  por Local-Visit
=> 60 issue 144 refactor sig partido

SMACB/Programa.py, SMACB/TemporadaACB.py
Refactoriza para usar namedtuples en las cosas relativas a configuración
Resuelve lo que quedaba de #144
=> Issue 144 refactor clasif liga

SMACB/Constants.py, SMACB/Programa.py, SMACB/TemporadaACB.py, bin/generaPrograma.py
=> 62 issue 149 tabla comparacion liga

SMACB/TemporadaACB.py
Refactor a medias y sin probar
Arregla #161
=> 63 casque iss 161

SMACB/Programa.py
=> [Bug] Arreglar problema en Trayectoria (por J17)

SMACB/Programa.py
No muestra que queda la jornada porjugar si no se ha jugado ningún partido de la misma
Trata #149
=> SMACB/Programa.py: quita pend Jornada a Tabla Liga

SMACB/Programa.py
Arregla #168 
Ya estaba hecho para equipos pero la lógica era mejorable.
Añadido para Max Min.
=> Revisa el sistema de ordenación en tabla de estadísticas

.flake8, Makefile, SMACB/Programa.py, bin/generaPrograma.py, requirements-dev.txt, requirements.txt
La línea incluye cuándo se han descargado los datos y cuándo se ha generado el programa así como explicación del origen de los datos
Resuelve #160
=> Añade línea con metadata

SMACB/Constants.py, SMACB/Programa.py, Utils/ReportLab/RLverticalText.py, bin/generaPrograma.py
Añade información sobre qué se está viendo
Trata Iss #112
=> Añade leyendas a las tablas

SMACB/PartidoACB.py, SMACB/Programa.py, SMACB/TemporadaACB.py, requirements-dev.txt, requirements.txt
=> Cambios tabla jugador

SMACB/Constants.py, SMACB/Programa.py, SMACB/TemporadaACB.py, requirements-dev.txt, requirements.txt
Añade cambios que faltaban en #112
=> 72 iss 112 leyenda 2

DescargaTemporada.py
=> 84 DescargaTemporada.py: cambia el texto de foto

SMACB/CalendarioACB.py, SMACB/FichaJugador.py, SMACB/PartidoACB.py, SMACB/PlantillaACB.py, SMACB/TemporadaACB.py, Utils/Web.py
De momento solo comprueba que tienen estadísticas. Si no está descargado correctamente no lo incorpora a la temporada. (Fixes #218 )
Saca la preparación de config,browser a una función externa
=> Iss 228 Comprueba si cada partido es descargado correctamente

.prospector.yaml, DescargaTemporada.py, SMACB/PartidoACB.py, SMACB/PlantillaACB.py, SMACB/Programa.py, SMACB/TemporadaACB.py, bin/generaPrograma.py
=> 87 iss232 problema con programa fcb

SMACB/FichaJugador.py
Arregla #239 
* Arregla salida para caso de jugador con pocos datos (sin ficha ni en plantilla pero ha jugado un partido)
* El tema latente de jugador que salía ("Nuevo fichaje de")
* Prospector
=> Arreglada la salida de nombreFich para jugador sin datos

SMACB/FichaJugador.py
Co-authored-by: cap@CASA <cap@CASA>
Fixes #239
=> Sync 20250106

SMACB/CalendarioACB.py, SMACB/Programa.py, SMACB/TemporadaACB.py, bin/generaPrograma.py, requirements.txt
* Arregla #234  Lo pone en su sitio en tabla de clasificación y trata cuando se solapa con las líneas existentes
* Arregla #243  No pone ref a partidos adelantados si la jornada adelantada se ha jugado entera
=> 89 iss234 Arreglos en programa: línea de perdedores

DescargaTemporada.py, SMACB/CalendarioACB.py, SMACB/DiferenciasTrasDescargaTemp.py, SMACB/TemporadaACB.py, Utils/FechaHora.py
* Hace #245 
* Resuelve #238  al mover todas las funciones de salida a una nueva librería en SMACB
=> 90 iss245 Refleja Cambios en el Calendario

Readme.md, SMACB/CalendarioACB.py, SMACB/Constants.py, SMACB/FichaJugador.py, SMACB/PartidoACB.py, SMACB/TemporadaACB.py, Utils/Web.py, Utils/combinatorics.py, scripts/getTemporada.sh
* Convert URLs to https
* scripts/getTemporada.sh: fija PYTHONPATH (resto Iss225)
* SMACB/CalendarioACB:compo2clave usa ahora RE en lugar de cadenas
---------
=> Sync 20250126

SMACB/DiferenciasTrasDescargaTemp.py, SMACB/FichaJugador.py, Utils/ParseoData.py
* Arreglado problema (por algún motivo no incluía la edad)
* Mejorados textos de jugador en mensajes de cambios
=> 94 iss256 arreglar excepcion al descargar el madrid

SMACB/DiferenciasTrasDescargaTemp.py, SMACB/FichaJugador.py, Utils/ParseoData.py
* Utils/ParseoData.py: Añadida edad (None)
* Cambios en trazas
* SMACB/FichaJugador.py: cambiado __repr__
---------
=> 94 iss256 arreglar excepcion al descargar el madrid (#258)

SMACB/Constants.py, SMACB/FichaJugador.py, Utils/ParseoData.py
Añade la URL con la locución de su nombre a la ficha del jugador
=> 95 iss260 comprobar si hay locucion

SMACB/Programa.py, bin/generaPrograma.py, requirements.txt
Añade parámetro para selección de tablas específicas de jugadores (la de Ultimo partido descuadraba el tema)
=> 98 iss265 quitar tabla de up

SMACB/PartidoACB.py
Iss274 problemas con re de jornada (#275)
---------
=> Sync 20250525

SMACB/CalendarioACB.py, SMACB/Constants.py, SMACB/PartidoACB.py, requirements.txt
Después de 10 años, la página de ACB distingue LR de Playoffs. Ajusta eso
=> Iss277 arreglar deteccion calendario playoffs

SMACB/CalendarioACB.py, SMACB/Constants.py, SMACB/Programa/Clasif.py, SMACB/Programa/Datos.py, SMACB/Programa/FuncionesAux.py, SMACB/Programa/Globals.py, SMACB/Programa/Paginas.py, SMACB/Programa/Presentacion.py, SMACB/Programa/Secciones.py, SMACB/TemporadaACB.py, bin/generaPrograma.py, requirements.txt
Tiene en cuenta todos los cambios para tratar que ya aparece info de Playoff.
Muestra en el programa que se trata de play off con estado de la serie, e información sobre precedentes.
=> 104 iss280 Ajusta programa a Playoffs
